export const FETCH_BUOYS_SUCCESS = 'FETCH_BUOYS_SUCCESS';
export const FETCH_BUOYS_FAIL = 'FETCH_BUOYS_FAIL';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAVORITE_FAIL = 'ADD_FAVORITE_FAIL';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_FAVORITE_FAIL = 'REMOVE_FAVORITE_FAIL';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';
